### PR TITLE
Feature/sort performance fixes

### PR DESCRIPTION
**Pull request by vade**
Hi! Thanks for this library, it's been awesome to work with! 

I made some minor tweaks related to sorting which got me some higher FPS ~~at the cost of some additional CPU churn~~

* replaced the swift async task call with a dedicated dispatch queue
* added some vdsp math to some areas of interest
* ~~added a dispatch concurrentPerform on embarrassingly parallel loop that only worked in place~~
  * It actually turns out I was over subscribing GCD here and just using an in place iteration was faster- turns out this can run at 120Hz w/o extra CPU usage. 
* cleaned up some memory semantics to allow for parallelization on the CPU  (re-allocation)

This took a sample splat prior from 80fps in my macOS metal app on an M1 Max 64 Gb to 120 FPS

Things that could make a large difference I haven't gotten to yet

* floating point radix sort on the depth rather than swift which should be faster
* In theory could even do GPU sorting but yeeeaaahhh

### CODE REVIEW

**Comment by scier** [comment]
Good find! There were a number of unrelated things in the PR so I tried them out separately, and the one that actually provided the nice 5% framerate win was removing the synchronous initialization of the temp buffer (though the SIMD tweaks are a nice cleanup and provide another improvement to sort performance). The dispatch queue didn't seem to provide any performance benefit as far as I could tell, nor did recreating the temp array on each sort. I have a [simplified version of this commit](https://github.com/scier/MetalSplatter/commit/6e348a80bae3e8c5ff048a0a9df005aa4c01ae12) I can push (which actually removes that initialization pass altogether) which I can push, if you don't have objections; or if you'd rather take a pass at reworking this to focus on just those changes, I can hold off.

**Comment by vade** [comment]
Hey there!

I think the dispatch queue being serial provides a clear semantic as well as re-entrant guarantee should any other locking hiccups happen that Swift Task doesnt have - thats all I was thinking there.

**Comment by vade** [comment]
And feel free to cherry pick! ofc :)

**Comment by scier** [comment]
Pushed as 6e348a80ba. Thank you!

**Pull request closed without merging**
